# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13fe16500e13664df5526553372212c39fd936537fc3ecd43f4df2427c3d94201a458b48bc6a969475ce4eba042624219cd9c87dc4725b91e005b5d0565a4e76

test:
  secret_key_base: c7dcae1c79388fad0905dbd1c9dfe148797f8ddcb157aa5d1c72ad3df396759d1086d704b6577a09a43f2c908be3aacfc9406e2ba1b948429f2c34c8ae4e717a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
